package site

import (
	"fmt"
	"strings"
)

// nginxInclude is the part of nginx.conf that follows the settings: the
// Content-Security-Policy, and /community, which the live demo links to.
func nginxInclude(s Settings) []byte {
	csp := strings.Join([]string{
		"default-src 'none'",
		"script-src 'self'",
		"style-src 'self'",
		"img-src 'self'",
		// The header's star count, once there are enough stars to show, and
		// this site, where audits like Lighthouse read robots.txt from the
		// page. img-src already lets a page ask this site for things.
		"connect-src 'self' https://api.github.com",
		"base-uri 'none'",
		"form-action 'none'",
		"frame-ancestors 'none'",
	}, "; ")
	return []byte(fmt.Sprintf(`# Generated by cmd/site from internal/site/settings.go; do not edit.
add_header Content-Security-Policy "%s" always;

# Where questions go (Settings.Community). The live demo links here, so it
# follows the setting without a rebuild of the dashboard.
location = /community {
    return 302 %s;
}
`, csp, s.Community.URL))
}
