package site

import (
	"fmt"
	"net/url"
	"slices"
	"strings"
)

// whopPixel is where Whop's ad pixel (Settings.WhopPixel) loads its scripts
// from and sends its events to.
const whopPixel = "https://t.whop.tw"

// nginxInclude is the part of nginx.conf that follows the settings: the
// Content-Security-Policy, /community, which the live demo links to, /start,
// and the channels' links.
func nginxInclude(s Settings) []byte {
	return []byte(fmt.Sprintf(`# Generated by cmd/site from internal/site/settings.go; do not edit.
# The Content-Security-Policy, and X-Robots-Tag where a page is kept out of
# search engines: a location changes them with set, not add_header, which
# would drop every header this server adds.
set $csp "%s";
set $robots "";
add_header Content-Security-Policy $csp always;
add_header X-Robots-Tag $robots always;

# Where questions go (Settings.Community). The live demo links here, so it
# follows the setting without a rebuild of the dashboard.
location = /community {
    return 302 %s;
}

# Where the Meta ads land. Its policy alone lets Whop's ad pixel in
# (Settings.WhopPixel), with the worker it starts from a blob, and the film.
# Kept out of search engines, and answered with no redirect, so the pixel
# still finds the ad's IDs in the query string.
location = /start {
    set $csp "%s";
    set $robots noindex;
    expires -1;
    try_files /start.html =404;
}

# Channel links (Settings.Channels): the landing page with the channel's UTM
# tags, where it shows the channel's install command.
%s`, contentSecurityPolicy(s, false), s.Community.URL, contentSecurityPolicy(s, true), channelLinks(s.Channels)))
}

// contentSecurityPolicy is the site's policy, or /start's.
func contentSecurityPolicy(s Settings, start bool) string {
	pixel := ""
	if start && s.WhopPixel != "" {
		pixel = whopPixel
	}
	d := []string{
		"default-src 'none'",
		"script-src " + sources("'self'", origin(s.Analytics.Script), pixel),
		"style-src 'self'",
		"img-src 'self'",
	}
	if start {
		d = append(d, "media-src 'self'")
	}
	if pixel != "" {
		d = append(d, "worker-src blob:")
	}
	return strings.Join(append(d,
		// The header's star count, once there are enough stars to show, and
		// this site, where audits like Lighthouse read robots.txt from the
		// page. img-src already lets a page ask this site for things. The
		// stats service takes copies of the install command.
		"connect-src "+sources("'self'", "https://api.github.com", origin(s.Analytics.Collector), origin(s.Stats), pixel),
		"base-uri 'none'",
		"form-action 'none'",
		"frame-ancestors 'none'",
	), "; ")
}

// sources is a directive's sources, leaving out empty ones.
func sources(list ...string) string {
	return strings.Join(slices.DeleteFunc(list, func(s string) bool { return s == "" }), " ")
}

// origin is an address's scheme and host, as a Content-Security-Policy source;
// empty for an empty address.
func origin(addr string) string {
	u, err := url.Parse(addr)
	if err != nil || u.Host == "" {
		return ""
	}
	return u.Scheme + "://" + u.Host
}
