#!/usr/bin/env bash
# Writes THIRD_PARTY_NOTICES: the full licence texts of the third-party code
# and art in the release binary. That is the Go standard library, every Go
# module the linux/amd64 release build links (go list -deps follows the same
# package graph as go build), the production npm packages bundled into the
# embedded web UI, the two small pieces of bundler code in that bundle (Vite's
# modulepreload polyfill and Rolldown's CommonJS helper), the coss ui
# components copied into the web UI's source, and the server software logos
# it shows.
# Needs the Go module cache and web/node_modules (scripts/setup.sh fills both).
# Usage: scripts/third-party-notices.sh [--check]
set -euo pipefail
export LC_ALL=C

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
export PATH="$root/.tools/go/bin:$root/.tools/node/bin:$PATH"
target=THIRD_PARTY_NOTICES
rule=$(printf '=%.0s' {1..80})
fail() {
  echo "third-party notices: $*" >&2
  exit 1
}

section() { # TITLE FILE...
  printf '%s\n%s\n%s\n' "$rule" "$1" "$rule"
  shift
  for f in "$@"; do
    printf '\n--- %s ---\n\n' "${f##*/}"
    awk 1 "$f"
  done
  printf '\n'
}

licence_files() { # DIR — prints the licence and notice files at the top of DIR
  local f name
  for f in "$1"/*; do
    [ -f "$f" ] || continue
    name=${f##*/}
    case ${name,,} in
      licen[cs]e* | copying* | notice*) printf '%s\n' "$f" ;;
    esac
  done
}

npm_version() { node -p "require(require('path').resolve(process.argv[1], 'package.json')).version" "$1"; }

generate() {
  local path version dir name files tmp
  cat <<'EOF'
Third-party notices for Playkeeper

Playkeeper is licensed under the GNU Affero General Public License, version 3
only; see LICENSE. The playkeeper binary also contains the third-party code
below, each part under its own licence, reproduced in full as those licences
require: the Go standard library, every Go module linked into the
linux/amd64 release build, the npm packages bundled into the embedded web
UI, the two small pieces of Vite and Rolldown code the bundler adds, the
coss ui components the web UI is built from, and the server software logos
it shows (each project's own, under the terms given with it).

Generated by scripts/third-party-notices.sh. Do not edit by hand.

EOF
  section "Go standard library and runtime ($(go env GOVERSION))" "$(go env GOROOT)/LICENSE"

  while read -r path version dir; do
    [ -n "$dir" ] || fail "Go module $path $version is not downloaded; run go mod download"
    mapfile -t files < <(licence_files "$dir")
    [ "${#files[@]}" -gt 0 ] || fail "no licence file in Go module $path $version ($dir)"
    section "$path $version (Go module)" "${files[@]}"
  done < <(GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go list -deps \
    -f '{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}' ./cmd/playkeeper | sort -u)

  while read -r dir; do
    name=${dir#"$root/web/node_modules/"}
    mapfile -t files < <(licence_files "$dir")
    [ "${#files[@]}" -gt 0 ] || fail "no licence file in npm package $name"
    section "$name $(npm_version "$dir") (npm package, bundled in the web UI)" "${files[@]}"
  done < <(cd web && npm ls --omit=dev --all --parseable | tail -n +2 | sort -u)

  dir=web/node_modules/rolldown
  section "rolldown $(npm_version "$dir") (its CommonJS runtime helper is bundled in the web UI)" \
    "$dir/LICENSE" "$dir/THIRD-PARTY-LICENSE"

  dir=web/node_modules/vite
  tmp=$(mktemp -d)
  awk '/^# Licenses of bundled dependencies/ {found = 1; exit}
    $0 == "" {blank++; next}
    {while (blank) {print ""; blank--} print}
    END {exit !found}' "$dir/LICENSE.md" >"$tmp/LICENSE.md" ||
    fail "$dir/LICENSE.md no longer has a 'Licenses of bundled dependencies' heading; check which part covers Vite's own code"
  section "vite $(npm_version "$dir") (its modulepreload polyfill is bundled in the web UI; Vite core licence only, as the rest of its LICENSE.md covers Vite's own build tooling)" \
    "$tmp/LICENSE.md"
  rm -rf "$tmp"

  section "coss ui (https://coss.com/ui): components copied into web/src/components/ui and bundled in the web UI" \
    web/src/components/ui/LICENSE.md

  dir=web/src/assets/logos
  section "Server software logos shown in the web UI (unaltered; each project's own, not covered by Playkeeper's licence)" \
    "$dir/NOTICE.md" "$dir"/licences/*
}

case ${1:-} in
  --check)
    fresh=$(mktemp)
    trap 'rm -f "$fresh"' EXIT
    generate >"$fresh"
    if ! cmp -s "$fresh" "$target"; then
      diff -u "$target" "$fresh" | head -40 >&2 || true
      fail "$target is out of date; run scripts/third-party-notices.sh (or make notices) and commit the result"
    fi
    echo "$target is up to date"
    ;;
  '')
    generate >"$target"
    echo "Wrote $target"
    ;;
  *) fail "usage: scripts/third-party-notices.sh [--check]" ;;
esac
