// Command sizing-guide writes the VPS sizing guide on playkeeper.io from
// internal/sizing: sizing.html from the template sizing.html.tmpl, with the
// table that works without JavaScript, and sizing-data.js, the answers the
// page's script shows for each choice. Run it with make sizing after changing
// either; a test fails while the committed files are out of date.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"html/template"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode/utf16"

	"github.com/CIYAhq/playkeeper/internal/sizing"
)

const (
	templateFile = "sizing.html.tmpl"
	pageFile     = "sizing.html"
	dataFile     = "sizing-data.js"

	// The answer the page shows first, as in the design.
	defaultPlayers  = 5
	defaultWorkload = sizing.Vanilla

	installCommand = "curl -fsSL https://playkeeper.io/install | sudo sh"
)

func main() {
	site := flag.String("site", "site", "the website's folder, which holds "+templateFile)
	flag.Parse()
	files, err := render(os.DirFS(*site))
	if err == nil {
		for _, name := range slices.Sorted(maps.Keys(files)) {
			if err = os.WriteFile(filepath.Join(*site, name), files[name], 0o644); err != nil {
				break
			}
			fmt.Println("wrote", filepath.Join(*site, name))
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "sizing-guide:", err)
		os.Exit(1)
	}
}

// view is what the page template shows.
type view struct {
	Notice    template.HTML
	Bands     []choice
	Workloads []choice
	RunLabel  string
	Answer    answer
	Rows      []row
	SystemGB  int
	Example   string
	Min       sizing.Machine
	Most      int
	Command   string
}

type choice struct {
	Key, Label, Description string
	Checked                 bool
}

// answer is one recommendation as the page words it.
type answer struct {
	Title    string   `json:"title"`
	Short    string   `json:"short"`
	Summary  string   `json:"summary"`
	Specs    string   `json:"specs"`
	Announce string   `json:"announce"`
	Reasons  []reason `json:"reasons"`
}

type reason struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Text  string `json:"text"`
}

type row struct {
	Band  string
	Cells []cell
}

type cell struct {
	ID, Memory, Cores, Disk string
}

func toAnswer(r sizing.Recommendation) answer {
	a := answer{
		Title:   r.Title,
		Short:   fmt.Sprintf("%d GB of memory", r.MemoryGB),
		Summary: r.Summary,
		Specs:   r.Reasons[1].Value + " · " + r.Reasons[2].Value,
	}
	a.Announce = fmt.Sprintf("%s, %s and %s.", r.Title, r.Reasons[1].Value, r.Reasons[2].Value)
	for _, x := range r.Reasons {
		a.Reasons = append(a.Reasons, reason{Label: x.Topic.Label(), Value: x.Value, Text: x.Text})
	}
	return a
}

func build() (view, map[string]map[string]answer, error) {
	first, err := sizing.Recommend(defaultWorkload, defaultPlayers)
	if err != nil {
		return view{}, nil, err
	}
	v := view{
		Notice:   "<!-- Generated by cmd/sizing-guide from " + templateFile + " and internal/sizing. Do not edit; run make sizing. -->",
		RunLabel: defaultWorkload.Label(),
		Answer:   toAnswer(first),
		SystemGB: first.Reasons[0].Params["systemMB"] / 1024,
		Min:      sizing.Machine{MemoryGB: sizing.MinMemoryGB, Cores: sizing.MinCores, DiskGB: sizing.MinFreeDiskGB},
		Most:     sizing.MaxPlayers,
		Command:  installCommand,
	}
	for _, b := range sizing.Bands() {
		v.Bands = append(v.Bands, choice{Key: b.Key(), Label: b.Label(), Checked: b == first.Band})
	}
	for _, w := range sizing.Workloads() {
		v.Workloads = append(v.Workloads, choice{Key: string(w), Label: w.Label(), Description: w.Description(), Checked: w == first.Workload})
	}
	answers := map[string]map[string]answer{}
	for _, r := range sizing.Table() {
		band := r.Band.Key()
		if answers[band] == nil {
			answers[band] = map[string]answer{}
			v.Rows = append(v.Rows, row{Band: r.Band.Label()})
		}
		answers[band][string(r.Workload)] = toAnswer(r)
		last := &v.Rows[len(v.Rows)-1]
		last.Cells = append(last.Cells, cell{
			ID:     "size-" + band + "-" + string(r.Workload),
			Memory: fmt.Sprintf("%d GB", r.MemoryGB),
			Cores:  fmt.Sprintf("%d cores", r.Cores),
			Disk:   fmt.Sprintf("%d GB disk", r.DiskGB),
		})
	}
	v.Example, err = example(v.SystemGB)
	return v, answers, err
}

// example works "several servers add up" through for two servers.
func example(systemGB int) (string, error) {
	planned := []struct {
		what   string
		server sizing.Server
	}{
		{"Paper", sizing.Server{Workload: sizing.Vanilla, Players: 10}},
		{"a big modpack", sizing.Server{Workload: sizing.Modpack, Players: 4}},
	}
	var servers []sizing.Server
	var parts, sum []string
	total := systemGB
	for _, p := range planned {
		r, err := sizing.Recommend(p.server.Workload, p.server.Players)
		if err != nil {
			return "", err
		}
		servers = append(servers, p.server)
		parts = append(parts, fmt.Sprintf("%s for %s friends (%d GB for the world)", p.what, r.Band.Label(), r.BudgetMB/1024))
		sum = append(sum, fmt.Sprint(r.BudgetMB/1024))
		total += r.BudgetMB / 1024
	}
	m, err := sizing.ForServers(servers)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("For example, %s: %s + %d = %d GB, so a VPS with %d GB of memory, %d fast cores and %d GB SSD.",
		strings.Join(parts, " and "), strings.Join(sum, " + "), systemGB, total, m.MemoryGB, m.Cores, m.DiskGB), nil
}

// render makes the guide's files from the template in site.
func render(site fs.FS) (map[string][]byte, error) {
	t, err := template.ParseFS(site, templateFile)
	if err != nil {
		return nil, fmt.Errorf("%w; run it from the repository root or pass -site with the website's folder", err)
	}
	v, answers, err := build()
	if err != nil {
		return nil, err
	}
	var page bytes.Buffer
	if err := t.Execute(&page, v); err != nil {
		return nil, err
	}
	js, err := json.MarshalIndent(map[string]any{"answers": answers}, "", "  ")
	if err != nil {
		return nil, err
	}
	data := "// Generated by cmd/sizing-guide from internal/sizing. Do not edit; run make sizing.\n" +
		"// The answers the sizing guide shows, by friends at once and what they run.\n" +
		"window.playkeeperSizing = " + ascii(string(js)) + ";\n"
	return map[string][]byte{pageFile: page.Bytes(), dataFile: []byte(data)}, nil
}

// ascii escapes everything past ASCII in JSON, so the script reads the same
// whatever character set it is served with.
func ascii(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r < 0x80 {
			b.WriteRune(r)
			continue
		}
		for _, u := range utf16.Encode([]rune{r}) {
			fmt.Fprintf(&b, `\u%04x`, u)
		}
	}
	return b.String()
}
